### ISSUE TITLE
Can't find executable file in Linux environment

### ISSUE THREAD

**Issue by RafikFarhad** [dj3500/hightail#101]
I use LinuxMint and Hightail is saying it can't find executable file.
What should I do?

**Comment by dj3500** [comment]
Hmm. Do you perhaps have spaces in your path? Someone on CF was reporting similar problems under MacOS.

**Comment by RafikFarhad** [comment]
Ni, I don't have spaces in my path.

**Comment by ankit2k48** [comment]
In linux, the executable file doesn't have any extension.. Try renaming ../prog.exe to ../prog in the Path to executable file.

Also make sure you compiled the .cpp file.

**Comment by dj3500** [comment]
@RafikFarhad have you resolved this?

**Comment by RafikFarhad** [comment]
No. I tried. But could not make it work. :(

**Comment by johnmts1** [comment]
i have same problem. How can i solve it?

**Comment by johnmts1** [comment]
i think that the file name should be without .exe . it should be only the file name. not only .exe but also .cpp

**Comment by johnmts1** [comment]
please fix it bro as soon as possible for linux users

**Comment by dj3500** [comment]
As far as I know, nothing is broken. You need to point it to your executable file. That file is not going to be called `a.exe` on Linux. It could be called e.g. `a.out` or just `a`.

**Comment by johnmts1** [comment]
But hightail always running when I use a. out
