### ISSUE TITLE
How long does Hightail run

### ISSUE THREAD

**Issue by gaddevarunteja** [dj3500/hightail#84]
Hightail keeps on running and is not stopping when I run it

`ant -f C:\\Users\\Varun\\Documents\\GitHub\\hightail\\Hightail -Dnb.internal.action.name=run run
init:
Deleting: C:\Users\Varun\Documents\GitHub\hightail\Hightail\build\built-jar.properties
deps-jar:
Updating property file: C:\Users\Varun\Documents\GitHub\hightail\Hightail\build\built-jar.properties
compile:
run:`

**Comment by dj3500** [comment]
I don't really understand. What happens if you run the .jar file? Does the window appear?
