### ISSUE TITLE
Hangs after running test cases once

### ISSUE THREAD

**Issue by mdtareque** [dj3500/hightail#85]
I am on ubuntu 15.10 and have download `Hightail-v0.9.4.jar`.

**Steps Done**
1. Open HighTail parse a single problem using <kbd>Ctrl</kbd> + <kbd>N</kbd>
2. Select the executable of respective program to test.
3. Click on 'Run tests'.

**Output**
It shows the correct Testing result, but then the HighTail window hangs, I cannot click on anything, nor I can close it. I have to force kill it via command-line.

Is this a known issue? Any info around this behaviour?

**Comment by dj3500** [comment]
Please post what program you're trying to run (source code, and how it is compiled). And what are the testcases that cause this behaviour.

**Comment by dj3500** [comment]
No reply, so closing.
