### ISSUE TITLE
Allow users to create their own contest offline 

### ISSUE THREAD

**Issue by UncleGrandpa925** [dj3500/hightail#86]

**Comment by UncleGrandpa925** [comment]
#Enhancement

**Comment by dj3500** [comment]
What do you mean?

**Comment by UncleGrandpa925** [comment]
I mean that currently I can't test multi problems at one time and that is quite inconvenient

**Comment by dj3500** [comment]
I still don't understand. Please explain better what the feature would be supposed to be, exactly.
