### ISSUE TITLE
Other Program when using the Hightail

### ISSUE THREAD

**Issue by wxjlzbcd** [dj3500/hightail#88]
I was using a c++ editor when running a exe in hightail.
However,the judge paused and I couldn't do anything to abort it or restart it.
After a long time,the first sample was "OK 46.999",while the second sample was "-".
But when I started the Hightail again,I closed my IDE and got OK in both two samples.
Can't I use my IDE when using the Hightail?Is it a coincidence?

My IDE was Dev-C++ 5.9.2.The OS is Windows 7 (64bits).

**Comment by dj3500** [comment]
Hard to say. No idea how to investigate this, so closing.
